pipeline{
    agent any
     tools {
  terraform 'Terraform-11'
   } 
    stages{
        stage('Terraform Init'){
            steps{
                sh label: '', script: 'terraform init'
            }
        }
        stage('Terraform Apply'){
            steps{
                sh label: '', script: 'terraform apply --auto-approve'
            }
        }
    }
}